server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
  lavasrc:
    sources:
      spotify: true
      youtube: true
    spotify:
      clientId: "c525956aba4945ca8e1f56b3c033cf9c"
      clientSecret: "c913ba2ccd764a698d6cd903874535ab"
      countryCode: "US"
      playlistLoadLimit: 6
      albumLoadLimit: 50
      resolveArtistsInSearch: true
      localFiles: false
    # applemusic:
    #  countryCode: "US"
    #  playlistLoadLimit: 6
    #  albumLoadLimit: 50
    # deezer:
    #  masterDecryptionKey: null
    twitch:
      clientId: null
      clientSecret: null
    providers:
      - "spsearch:{QUERY}" # Spotify search
      - "ytsearch:{QUERY}" # YouTube search as the primary source
      - "ytmsearch:{QUERY}" # YouTube Music search
      - "sprec:{QUERY}" # Spotify recommendations

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      spotify: false
      vimeo: true
      http: true
      local: false
    plugins:
      - className: "dev.arbjerg.lavalink.plugins.youtube.YoutubePlugin"
        path: "./plugins/youtube-plugin-1.8.3.jar"
      - className: "com.github.topi314.lavasrc.plugin.LavaSrcPlugin"
        path: "./plugins/lavasrc-plugin-4.3.0.jar"
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 5
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 15
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    httpConfig:
      forwardHeaders: true
    pluginsDir: "./plugins"
    youtubeConfig:
      enabled: true
      allowSearch: true
      allowDirectVideoIds: true
      allowDirectPlaylistIds: true
      clients:
        - MUSIC
        - ANDROID_VR
        - WEB
        - WEBEMBEDDED

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: TRACE
    com.sedmelluq: TRACE
    dev.arbjerg.lavalink.plugins: DEBUG
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
