version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=${PG_DATABASE_URL}
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M