version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=${PG_DATABASE_URL}
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        # limits: # Removed memory limit
        #   memory: 512M
        reservations:
          memory: 128M # Keep reservation (can be lowered cautiously)
