[phases.setup]
nixPkgs = ["bun", "openssl"]
aptPkgs = ["openssl"]

[phases.install]
cmds = [
    "bun install --no-postinstall=false",
    "bun add -d prisma@6.2.0"
]

[start]
cmd = "bunx prisma generate && bunx prisma migrate deploy && bun ."

[phases.cache]
directories = ["node_modules", "bun.lockb", "node_modules/.prisma"]
