[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install --no-postinstall=false"]

[phases.build]
cmds = ["bunx prisma generate"]

[start]
cmd = "bun ."

[phases.cache]
directories = ["node_modules", "bun.lockb", "node_modules/.prisma"]
