[phases.setup]
nixPkgs = ["bun", "unzip"]

[phases.install]
cmds = ["bun upgrade", "bun install --no-postinstall=false"]

[start]
cmd = "bun ."

[phases.cache]
directories = ["node_modules", "bun.lockb"]
